name: Publish output

on:
  workflow_dispatch: {}
  #schedule:
  #  - cron: '2 15 1 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true

jobs:
  cd:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run ci
      - run: |
          git config --global user.name 'Thomas Nemer'
          git config --global user.email 'atom@fortytwo.fr'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - run: mise run publish-output
